use DB_DEMO
CREATE TABLE AUTHOR(
AUTH_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(MAX),
COUNTRY VARCHAR(MAX)
)

create table book
(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(MAX),
AUTHID INT
FOREIGN KEY (AUTHID) REFERENCES AUTHOR(AUTH_ID)
)
INSERT INTO AUTHOR(AUTH_ID,EMP_NAME,COUNTRY) VALUES(102,'B','C2'),(103,'C','C3')
INSERT INTO book(BOOK_ID,BOOK_NAME,AUTHID) VALUES(1,'a',101),(2,'b',102),(3,'c',103)
truncate table book
SELECT* FROM AUTHOR
select* from AUTHOR as A 
inner join 
book as b on
b.BOOK_ID = A.AUTH_ID