--EASY LEVEL--

CREATE TABLE E(EMPID INT )

INSERT INTO E VALUES(2),(4),(4),(6),(6),(7),(8),(8)

SELECT MAX(EMPID) AS [EMPID] FROM E WHERE EMPID NOT IN
(SELECT EMPID FROM E GROUP BY EMPID HAVING COUNT(*) >1)

CREATE TABLE TBL_PRODUCTS
(
	ID INT PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(50),
	[DESCRIPTION] NVARCHAR(250) 
)

CREATE TABLE TBL_PRODUCTSALES
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUCTID INT FOREIGN KEY REFERENCES TBL_PRODUCTS(ID),
	UNITPRICE INT,
	QUALTITYSOLD INT
)

INSERT INTO TBL_PRODUCTS VALUES ('TV','52 INCH BLACK COLOR LCD TV')
INSERT INTO TBL_PRODUCTS VALUES ('LAPTOP','VERY THIIN BLACK COLOR ACER LAPTOP')
INSERT INTO TBL_PRODUCTS VALUES ('DESKTOP','HP HIGH PERFORMANCE DESKTOP')

INSERT INTO TBL_PRODUCTSALES VALUES (3,450,5)
INSERT INTO TBL_PRODUCTSALES VALUES (2,250,7)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,4)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,9)

SELECT *FROM TBL_PRODUCTS
SELECT *FROM TBL_PRODUCTSALES


SELECT P.ID, P.NAME, P.DESCRIPTION FROM TBL_PRODUCTS AS P WHERE P.ID NOT IN
(SELECT DISTINCT(S.PRODUCTID) FROM TBL_PRODUCTSALES AS S )

SELECT [NAME] ,
(SELECT SUM(QUALTITYSOLD) FROM TBL_PRODUCTSALES WHERE PRODUCTID = TBL_PRODUCTS.ID ) AS [TOTAL] 
FROM TBL_PRODUCTS


--------------------EXPERIMENT 03: (MEDIUM LEVEL)
CREATE TABLE department (
    id INT PRIMARY KEY,
    dept_name VARCHAR(50)
);

-- Create Employee Table
CREATE TABLE employee (
    id INT,
    name VARCHAR(50),
    salary INT,
    department_id INT,
    FOREIGN KEY (department_id) REFERENCES department(id)
);

-- Insert into Department Table
INSERT INTO department (id, dept_name) VALUES
(1, 'IT'),
(2, 'SALES');

-- Insert into Employee Table
INSERT INTO employee (id, name, salary, department_id) VALUES
(1, 'JOE', 70000, 1),
(2, 'JIM', 90000, 1),
(3, 'HENRY', 80000, 2),
(4, 'SAM', 60000, 2),
(5, 'MAX', 90000, 1);

SELECT * FROM employee
SELECT * FROM department

SELECT D.DEPT_NAME , E.NAME , E.salary 
FROM 
EMPLOYEE AS E
INNER JOIN 
department AS D
ON
D.ID = E.department_id
WHERE salary IN
(
	SELECT MAX(SALARY)
	FROM
	employee AS E2
	WHERE E2.department_id = E.department_id
)
ORDER BY D.DEPT_NAME


-----EXP03 ---------HARD-----------

CREATE TABLE A
(	EMPID INT PRIMARY KEY,
	ENAME VARCHAR(MAX),
	SALARY INT
)

CREATE TABLE B
(	EMPID INT PRIMARY KEY,
	ENAME VARCHAR(MAX),
	SALARY INT
)

INSERT INTO A VALUES (1,'AA', 5000),
					 (2,'BB', 3000)


INSERT INTO B VALUES (2,'BB', 7000),
					 (3,'CC', 4000)

SELECT * FROM A
SELECT * FROM B

SELECT EMPID , MIN(ENAME) AS ENAME , MIN(SALARY) AS SALARY
FROM
(
	SELECT * FROM A
	UNION ALL
	SELECT * FROM B
) AS INTERMEDIATE_RESULT
GROUP BY EMPID
